# Generated by Django 5.0.6 on 2024-06-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0003_alter_inventory_stock_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatted_date', models.DateTimeField()),
                ('summary', models.CharField(max_length=200)),
                ('precip_type', models.CharField(blank=True, max_length=50, null=True)),
                ('temperature_c', models.FloatField()),
                ('apparent_temperature_c', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed_kmh', models.FloatField()),
                ('wind_bearing_degrees', models.IntegerField()),
                ('visibility_km', models.FloatField()),
                ('cloud_cover', models.FloatField()),
                ('pressure_millibars', models.FloatField()),
                ('daily_summary', models.TextField()),
            ],
        ),
    ]
