# Generated by Django 5.0.6 on 2024-06-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0004_weather'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='cloud_cover',
            new_name='loud_cover',
        ),
    ]
