# Generated by Django 5.0.6 on 2024-06-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0005_rename_cloud_cover_weather_loud_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_link', models.URLField()),
                ('series_title', models.CharField(max_length=255)),
                ('released_year', models.IntegerField()),
                ('certificate', models.CharField(max_length=10)),
                ('runtime', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=255)),
                ('imdb_rating', models.FloatField()),
                ('overview', models.TextField()),
                ('meta_score', models.IntegerField()),
                ('director', models.CharField(max_length=255)),
                ('star1', models.CharField(max_length=255)),
                ('star2', models.CharField(max_length=255)),
                ('star3', models.CharField(max_length=255)),
                ('star4', models.CharField(max_length=255)),
                ('no_of_votes', models.IntegerField()),
                ('gross', models.CharField(max_length=255)),
            ],
        ),
    ]
