# Generated by Django 5.0.6 on 2024-06-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0006_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='meta_score',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='released_year',
            field=models.CharField(max_length=10),
        ),
    ]
