# Generated by Django 5.0.6 on 2024-06-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0008_queryhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_reference', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=10)),
                ('data_value', models.CharField(blank=True, max_length=20, null=True)),
                ('suppressed', models.CharField(blank=True, max_length=1)),
                ('status', models.CharField(max_length=1)),
                ('units', models.CharField(max_length=20)),
                ('magnitude', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('series_title_1', models.CharField(max_length=100)),
                ('series_title_2', models.CharField(max_length=100)),
                ('series_title_3', models.CharField(max_length=100)),
                ('series_title_4', models.CharField(blank=True, max_length=100)),
                ('series_title_5', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('customer_id', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('phone_1', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_2', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('subscription_date', models.DateField()),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_reference', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=10)),
                ('data_value', models.CharField(blank=True, max_length=20, null=True)),
                ('suppressed', models.CharField(blank=True, max_length=1)),
                ('status', models.CharField(max_length=1)),
                ('units', models.CharField(max_length=20)),
                ('magnitude', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('series_title_1', models.CharField(max_length=100)),
                ('series_title_2', models.CharField(blank=True, max_length=100, null=True)),
                ('series_title_3', models.CharField(blank=True, max_length=100, null=True)),
                ('series_title_4', models.CharField(blank=True, max_length=100, null=True)),
                ('series_title_5', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('organization_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('founded', models.IntegerField()),
                ('industry', models.CharField(max_length=100)),
                ('number_of_employees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('job_title', models.CharField(max_length=100)),
            ],
        ),
    ]
