# Generated by Django 5.0.6 on 2024-06-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('embed1', models.CharField(max_length=1000)),
                ('embed2', models.CharField(max_length=1000)),
                ('embed3', models.CharField(max_length=1000)),
            ],
        ),
    ]
