# Generated by Django 5.0.6 on 2024-06-14 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
