# Generated by Django 5.0.6 on 2024-06-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeds',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
